export type SettingType =
  | 'count' | 'minutes' | 'ratio' | 'boolean' | 'select'
  | 'currency' | 'score' | 'coefficient' | 'hours' | 'seconds' | 'km' | 'volume';

export interface SettingDef {
  key: string;
  label: string;
  unit: string;
  type: SettingType;
  defaultValue: number | boolean | string;
  min?: number;
  max?: number;
  step?: number;
  options?: string[];
  explanation: string;
  category: string;
  weightGroup?: string;
}

export interface CategoryDef {
  key: string;
  label: string;
  icon: string;
  formula?: string;
  formulaVars?: string;
}

export const CATEGORIES: CategoryDef[] = [
  { key: 'flow',        label: 'إعدادات التدفق',                    icon: '⟲' },
  { key: 'batch',       label: 'إعدادات الدفعة',                    icon: '▦' },
  { key: 'urgency',     label: 'إعدادات الأولوية',                  icon: '⚡' },
  {
    key: 'scoring',
    label: 'أوزان تقييم الدفعات',
    icon: '⊞',
    formula: 'Score = W_n × N̂ + W_u × Û − W_d × D̂',
    formulaVars: 'N̂ = عدد الشحنات  ·  Û = الأولوية  ·  D̂ = مدة المسار',
  },
  { key: 'dead_end',    label: 'إعدادات النهايات المسدودة',         icon: '⊘' },
  {
    key: 'cost',
    label: 'إعدادات التكلفة',
    icon: '₪',
    formula: 'cost = dist × CPK + dur × CPM + stops × CPS + FDC',
    formulaVars: 'CPK = تكلفة/كم  ·  CPM = تكلفة/دقيقة  ·  CPS = تكلفة/محطة  ·  FDC = تكلفة الإرسال الثابتة',
  },
  { key: 'zone_c',      label: 'توسيع المنطقة C',                   icon: '→C' },
  { key: 'reservation', label: 'إعدادات الحجز',                     icon: '⏳' },
  { key: 'delay',       label: 'إعدادات التأخير',                   icon: '⏸' },
  { key: 'in_transit',  label: 'الإضافات أثناء الرحلة',             icon: '⊕' },
  {
    key: 'intra_city',
    label: 'ترتيب المحطات الداخلية',
    icon: '◎',
    formula: 'task_score = W_dist × distance − W_urg × urgency_score',
    formulaVars: 'النقاط الأقل = أولوية أعلى للزيارة',
  },
  {
    key: 'driver',
    label: 'تعيين السائق',
    icon: '◈',
    formula: 'Driver_Score = W_prox × P + W_cap × C − W_load × L',
    formulaVars: 'P = تناقص القرب  ·  C = ملاءمة السعة  ·  L = معامل الإرهاق',
  },
  { key: 'breakdown',   label: 'إعدادات الأعطال',                   icon: '⚠' },
];

export const WEIGHT_GROUPS: Record<string, { label: string; keys: string[] }> = {
  batch_score_weights: {
    label: 'أوزان تقييم الدفعات',
    keys: ['WEIGHT_SHIPMENT_COUNT', 'WEIGHT_URGENCY', 'WEIGHT_DURATION'],
  },
  intra_city_weights: {
    label: 'أوزان المسار الداخلي',
    keys: ['WEIGHT_STOP_DISTANCE', 'WEIGHT_STOP_URGENCY'],
  },
  driver_weights: {
    label: 'أوزان تعيين السائق',
    keys: ['WEIGHT_DRIVER_PROXIMITY', 'WEIGHT_DRIVER_CAPACITY', 'WEIGHT_DRIVER_LOAD'],
  },
};

export const SETTINGS_DEFINITIONS: SettingDef[] = [
  // ── 1. إعدادات التدفق ───────────────────────────────────────────────────────
  // Phase 0 groups all available and delayed shipments by direction (pickup_zone → dropoff_zone).
  // No flow is rejected at this stage. Low-count decisions are handled in Phase 0b using
  // MIN_BATCH_THRESHOLD, urgency override, and MAX_FLOW_WAITING_TIME rules.
  {
    key: 'FLOW_GROUPING_WINDOW_MINUTES',
    label: 'نافذة تجميع التدفق',
    unit: 'دقيقة',
    type: 'minutes',
    defaultValue: 30,
    min: 5,
    max: 240,
    step: 5,
    explanation: 'كم مرة تعمل دورة التجميع وتُجمّع الشحنات المتاحة حسب مناطق الاستلام والتوصيل.',
    category: 'flow',
  },
  {
    key: 'MAX_FLOW_WAITING_TIME',
    label: 'أقصى وقت انتظار التدفق',
    unit: 'دقيقة',
    type: 'minutes',
    defaultValue: 120,
    min: 10,
    max: 7200,
    step: 10,
    explanation: 'أقصى وقت قبل قيام النظام برفع أولوية التدفق أو تصعيده.',
    category: 'flow',
  },

  // ── 2. إعدادات الدفعة ──────────────────────────────────────────────────────
  {
    key: 'MIN_BATCH_THRESHOLD',
    label: 'الحد الأدنى للدفعة',
    unit: 'شحنة',
    type: 'count',
    defaultValue: 5,
    min: 1,
    max: 50,
    step: 1,
    explanation: 'أدنى عدد شحنات مطلوب لإرسال الدفعة. إذا كان العدد أقل وليست الشحنات عاجلة تُؤجَّل للدورة التالية.',
    category: 'batch',
  },
  {
    key: 'MAX_SHIPMENTS_PER_BATCH',
    label: 'أقصى شحنات في الدفعة',
    unit: 'شحنة',
    type: 'count',
    defaultValue: 20,
    min: 1,
    max: 200,
    step: 1,
    explanation: 'الحد الأقصى لعدد الشحنات المسموح بها في دفعة واحدة.',
    category: 'batch',
  },
  {
    key: 'MAX_STOPS_PER_BATCH',
    label: 'أقصى محطات في الدفعة',
    unit: 'محطة',
    type: 'count',
    defaultValue: 20,
    min: 1,
    max: 100,
    step: 1,
    explanation: 'الحد الأقصى لعدد محطات الاستلام أو التسليم المسموح بها في دفعة واحدة.',
    category: 'batch',
  },
  {
    key: 'MAX_VOLUME_PER_BATCH',
    label: 'أقصى حجم في الدفعة',
    unit: 'وحدة حجم',
    type: 'volume',
    defaultValue: 100,
    min: 1,
    max: 10000,
    step: 1,
    explanation: 'أقصى سعة يمكن لمركبة السائق حملها في رحلة واحدة.',
    category: 'batch',
  },
  {
    key: 'ALLOW_SINGLE_URGENT_SHIPMENT',
    label: 'السماح بشحنة عاجلة منفردة',
    unit: 'نعم/لا',
    type: 'boolean',
    defaultValue: false,
    explanation: 'يسمح بإرسال شحنة عاجلة واحدة دون بلوغ الحد الأدنى للدفعة.',
    category: 'batch',
  },
  {
    key: 'MAX_WAIT_DAYS',
    label: 'أقصى أيام انتظار الشحنة',
    unit: 'يوم',
    type: 'count',
    defaultValue: 3,
    min: 1,
    max: 30,
    step: 1,
    explanation: 'الحد الأقصى لعدد الأيام التي تنتظرها الشحنة قبل الاستلام — يُحسب الموعد النهائي تلقائياً عند إنشاء الشحنة بناءً على هذه القيمة.',
    category: 'batch',
  },

  // ── 3. إعدادات الأولوية ────────────────────────────────────────────────────
  {
    key: 'URGENCY_OVERRIDE_WINDOW_MINUTES',
    label: 'نافذة تجاوز الأولوية',
    unit: 'دقيقة',
    type: 'minutes',
    defaultValue: 120,
    min: 10,
    max: 480,
    step: 10,
    explanation: 'إذا كان الموعد النهائي للشحنة ضمن هذه الفترة، تُرسَل فوراً حتى لو كانت الدفعة صغيرة.',
    category: 'urgency',
  },
  {
    key: 'URGENCY_THRESHOLD',
    label: 'عتبة الأولوية',
    unit: '0 – 1',
    type: 'ratio',
    defaultValue: 0.7,
    min: 0,
    max: 1,
    step: 0.01,
    explanation: 'درجة الأولوية التي فوقها تُعتبر الشحنة أو التدفق عاجلاً.',
    category: 'urgency',
  },
  {
    key: 'DELAYED_ESCALATION_WINDOW_MINUTES',
    label: 'نافذة تصعيد التأخير',
    unit: 'دقيقة',
    type: 'minutes',
    defaultValue: 30,
    min: 5,
    max: 240,
    step: 5,
    explanation: 'الفترة الزمنية لتصعيد الشحنات المؤجلة القريبة من موعدها النهائي.',
    category: 'urgency',
  },
  {
    key: 'WAITING_TIME_WEIGHT',
    label: 'وزن وقت الانتظار',
    unit: 'نسبة',
    type: 'ratio',
    defaultValue: 0.5,
    min: 0,
    max: 1,
    step: 0.01,
    explanation: 'كم يُسهم وقت الانتظار في حساب درجة الأولوية.',
    category: 'urgency',
  },
  {
    key: 'DEADLINE_WEIGHT',
    label: 'وزن قرب الموعد النهائي',
    unit: 'نسبة',
    type: 'ratio',
    defaultValue: 0.5,
    min: 0,
    max: 1,
    step: 0.01,
    explanation: 'كم يُسهم قرب الموعد النهائي في حساب درجة الأولوية.',
    category: 'urgency',
  },

  // ── 4. أوزان تقييم الدفعات ─────────────────────────────────────────────────
  {
    key: 'WEIGHT_SHIPMENT_COUNT',
    label: 'وزن عدد الشحنات (W_n)',
    unit: 'نسبة',
    type: 'ratio',
    defaultValue: 0.35,
    min: 0,
    max: 1,
    step: 0.01,
    explanation: 'يتحكم في تأثير عدد الشحنات على أولوية الدفعة. قيمة أعلى = عدد شحنات أكبر يرفع التقييم.',
    category: 'scoring',
    weightGroup: 'batch_score_weights',
  },
  {
    key: 'WEIGHT_URGENCY',
    label: 'وزن الأولوية (W_u)',
    unit: 'نسبة',
    type: 'ratio',
    defaultValue: 0.45,
    min: 0,
    max: 1,
    step: 0.01,
    explanation: 'يتحكم في تأثير الأولوية على ترتيب الدفعات. قيمة أعلى = الدفعات الأشد إلحاحاً تُرسَل أولاً.',
    category: 'scoring',
    weightGroup: 'batch_score_weights',
  },
  {
    key: 'WEIGHT_DURATION',
    label: 'وزن مدة المسار (W_d)',
    unit: 'نسبة',
    type: 'ratio',
    defaultValue: 0.20,
    min: 0,
    max: 1,
    step: 0.01,
    explanation: 'يتحكم في عقوبة المسارات الطويلة. قيمة أعلى = المسارات الأطول تُخفَّض أولويتها بشكل أكبر.',
    category: 'scoring',
    weightGroup: 'batch_score_weights',
  },
  {
    key: 'NORMALIZATION_METHOD',
    label: 'طريقة التطبيع',
    unit: 'أسلوب',
    type: 'select',
    defaultValue: 'min-max',
    options: ['min-max', 'z-score', 'max'],
    explanation: 'أسلوب تحويل العوامل المختلفة إلى نطاق 0–1 قبل تطبيق الأوزان. الأكثر شيوعاً هو min-max.',
    category: 'scoring',
  },

  // ── 5. إعدادات النهايات المسدودة ────────────────────────────────────────────
  {
    key: 'ENABLE_DEAD_END_CHECK',
    label: 'تفعيل فحص النهايات المسدودة',
    unit: 'نعم/لا',
    type: 'boolean',
    defaultValue: true,
    explanation: 'يتحقق من وجود طلب صادر من منطقة الوجهة قبل الالتزام بالمسار.',
    category: 'dead_end',
  },
  {
    key: 'BASE_DEAD_END_PENALTY',
    label: 'عقوبة النهاية المسدودة الأساسية',
    unit: 'نقاط',
    type: 'score',
    defaultValue: 0.2,
    min: 0,
    max: 1,
    step: 0.01,
    explanation: 'العقوبة المطروحة من تقييم الدفعة عند غياب الطلب في منطقة الوجهة. المعادلة: penalty = BASE_PENALTY × (1 − Û)',
    category: 'dead_end',
  },
  {
    key: 'DEAD_END_MIN_URGENCY_BYPASS',
    label: 'تجاوز الأولوية للنهاية المسدودة',
    unit: '0 – 1',
    type: 'ratio',
    defaultValue: 0.8,
    min: 0,
    max: 1,
    step: 0.01,
    explanation: 'إذا تجاوزت أولوية الدفعة هذا الحد، تُلغى العقوبة تماماً بصرف النظر عن الطلب في منطقة الوجهة.',
    category: 'dead_end',
  },

  // ── 6. إعدادات التكلفة ──────────────────────────────────────────────────────
  {
    key: 'COST_PER_KM',
    label: 'التكلفة لكل كيلومتر',
    unit: '₪/كم',
    type: 'currency',
    defaultValue: 2.5,
    min: 0,
    max: 100,
    step: 0.1,
    explanation: 'التكلفة المحسوبة لكل كيلومتر تقطعه المركبة. تُستخدم في فحوصات الجدوى لمقارنة التمديد مقابل الإرسال الجديد.',
    category: 'cost',
  },
  {
    key: 'COST_PER_MINUTE',
    label: 'التكلفة لكل دقيقة',
    unit: '₪/د',
    type: 'currency',
    defaultValue: 0.5,
    min: 0,
    max: 50,
    step: 0.1,
    explanation: 'التكلفة الزمنية لكل دقيقة سفر، تشمل تكاليف السائق والتشغيل.',
    category: 'cost',
  },
  {
    key: 'COST_PER_STOP',
    label: 'التكلفة لكل محطة',
    unit: '₪/محطة',
    type: 'currency',
    defaultValue: 1.0,
    min: 0,
    max: 100,
    step: 0.5,
    explanation: 'التكلفة لكل محطة استلام أو تسليم، تشمل وقت المناولة والتكاليف الإدارية لكل موقع.',
    category: 'cost',
  },
  {
    key: 'FIXED_DISPATCH_COST',
    label: 'تكلفة الإرسال الثابتة',
    unit: '₪',
    type: 'currency',
    defaultValue: 10,
    min: 0,
    max: 1000,
    step: 0.5,
    explanation: 'تكلفة ثابتة تُضاف في كل مرة يُرسَل فيها سائق جديد لدفعة.',
    category: 'cost',
  },
  {
    key: 'RETURN_TO_BASE_ENABLED',
    label: 'تفعيل تكلفة العودة للقاعدة',
    unit: 'نعم/لا',
    type: 'boolean',
    defaultValue: true,
    explanation: 'عند التفعيل، يُدرج النظام تكلفة عودة السائق لقاعدته في حساب الجدوى.',
    category: 'cost',
  },
  {
    key: 'MAX_ROUTE_COST',
    label: 'أقصى تكلفة للمسار',
    unit: '₪',
    type: 'currency',
    defaultValue: 500,
    min: 0,
    max: 10000,
    step: 10,
    explanation: 'الحد الأقصى للتكلفة الكلية لمسار واحد. المسارات التي تتجاوز هذا الحد تُحظر.',
    category: 'cost',
  },

  // ── 7. توسيع المنطقة C ──────────────────────────────────────────────────────
  {
    key: 'ENABLE_ZONE_C_EXTENSION',
    label: 'تفعيل توسيع المنطقة C',
    unit: 'نعم/لا',
    type: 'boolean',
    defaultValue: true,
    explanation: 'يتيح تمديد المسار من أ→ب إلى أ→ب→ج عند الجدوى الاقتصادية.',
    category: 'zone_c',
  },
  {
    key: 'MAX_ZONES_PER_ROUTE',
    label: 'أقصى مناطق في المسار',
    unit: 'منطقة',
    type: 'count',
    defaultValue: 3,
    min: 2,
    max: 5,
    step: 1,
    explanation: 'الحد الأقصى لعدد المناطق (المدن) المسموح بها في مسار واحد.',
    category: 'zone_c',
  },
  {
    key: 'MAX_ROUTE_DURATION_MINUTES',
    label: 'أقصى مدة المسار',
    unit: 'دقيقة',
    type: 'minutes',
    defaultValue: 240,
    min: 30,
    max: 720,
    step: 15,
    explanation: 'أقصى وقت مسموح به للمسار الكامل شاملاً جميع المقاطع.',
    category: 'zone_c',
  },
  {
    key: 'MAX_EXTRA_DISTANCE_KM',
    label: 'أقصى مسافة إضافية',
    unit: 'كم',
    type: 'km',
    defaultValue: 50,
    min: 0,
    max: 500,
    step: 5,
    explanation: 'أقصى مسافة إضافية مسموح بها عند إضافة المنطقة C للمسار.',
    category: 'zone_c',
  },
  {
    key: 'MIN_SAVINGS_TO_EXTEND',
    label: 'أدنى وفر لتمديد المسار',
    unit: '₪',
    type: 'currency',
    defaultValue: 20,
    min: 0,
    max: 500,
    step: 5,
    explanation: 'أدنى توفير مطلوب في التكلفة قبل تمديد المسار للمنطقة C.',
    category: 'zone_c',
  },
  {
    key: 'ZONE_C_MIN_BATCH_THRESHOLD',
    label: 'الحد الأدنى لدفعة المنطقة C',
    unit: 'شحنة',
    type: 'count',
    defaultValue: 3,
    min: 1,
    max: 50,
    step: 1,
    explanation: 'أدنى عدد شحنات مطلوب للمقطع ب→ج حتى يُؤخذ بعين الاعتبار.',
    category: 'zone_c',
  },
  {
    key: 'ZONE_C_URGENCY_THRESHOLD',
    label: 'عتبة أولوية المنطقة C',
    unit: '0 – 1',
    type: 'ratio',
    defaultValue: 0.7,
    min: 0,
    max: 1,
    step: 0.01,
    explanation: 'عتبة الأولوية التي تُفعّل دفعة طارئة للمنطقة C حتى لو لم تكن الخيار الأمثل.',
    category: 'zone_c',
  },

  // ── 8. إعدادات الحجز ───────────────────────────────────────────────────────
  {
    key: 'RESERVATION_BUFFER_MINUTES',
    label: 'احتياطي وقت الحجز',
    unit: 'دقيقة',
    type: 'minutes',
    defaultValue: 30,
    min: 0,
    max: 120,
    step: 5,
    explanation: 'وقت إضافي يُضاف لمدة الحجز لشحنات ب→ج كحماية من التأخيرات الطفيفة.',
    category: 'reservation',
  },
  {
    key: 'MAX_RESERVATION_TTL_MINUTES',
    label: 'أقصى مدة الحجز',
    unit: 'دقيقة',
    type: 'minutes',
    defaultValue: 180,
    min: 30,
    max: 1440,
    step: 15,
    explanation: 'أقصى وقت تبقى فيه الشحنة في حالة "محجوزة" قبل إلغاء الحجز تلقائياً.',
    category: 'reservation',
  },
  {
    key: 'RELEASE_EXPIRED_RESERVATIONS_INTERVAL',
    label: 'فترة تحرير الحجوزات',
    unit: 'دقيقة',
    type: 'minutes',
    defaultValue: 5,
    min: 1,
    max: 60,
    step: 1,
    explanation: 'مدة تكرار مهمة التحقق من الحجوزات المنتهية وإلغائها تلقائياً.',
    category: 'reservation',
  },

  // ── 9. إعدادات التأخير ─────────────────────────────────────────────────────
  {
    key: 'DELAY_CYCLE_INTERVAL_MINUTES',
    label: 'فترة دورة التأخير',
    unit: 'دقيقة',
    type: 'minutes',
    defaultValue: 30,
    min: 5,
    max: 240,
    step: 5,
    explanation: 'المدة التي تنتظرها الشحنة المؤجلة قبل إعادة دخولها دورة التجميع.',
    category: 'delay',
  },
  {
    key: 'MAX_DELAY_COUNT',
    label: 'أقصى مرات التأخير',
    unit: 'مرة',
    type: 'count',
    defaultValue: 3,
    min: 1,
    max: 20,
    step: 1,
    explanation: 'أقصى عدد مرات تأجيل الشحنة قبل الإرسال القسري.',
    category: 'delay',
  },
  {
    key: 'FORCE_DISPATCH_AFTER_DELAY_COUNT',
    label: 'إرسال قسري بعد التأخيرات القصوى',
    unit: 'نعم/لا',
    type: 'boolean',
    defaultValue: true,
    explanation: 'يُجبر على الإرسال بعد بلوغ الحد الأقصى للتأخيرات بغض النظر عن حجم الدفعة.',
    category: 'delay',
  },

  // ── 10. الإضافات أثناء الرحلة ───────────────────────────────────────────────
  {
    key: 'ENABLE_IN_TRANSIT_ADDITIONS',
    label: 'تفعيل الإضافات أثناء الرحلة',
    unit: 'نعم/لا',
    type: 'boolean',
    defaultValue: true,
    explanation: 'يتيح إضافة شحنات ب→ج جديدة للدفعة بينما السائق في طريقه للمنطقة ب.',
    category: 'in_transit',
  },
  {
    key: 'MIN_TIME_TO_ZONE_B_FOR_ADDITION',
    label: 'أدنى وقت للوصول للمنطقة ب قبل الإضافة',
    unit: 'دقيقة',
    type: 'minutes',
    defaultValue: 15,
    min: 5,
    max: 120,
    step: 5,
    explanation: 'أدنى وقت متبقٍ للوصول للمنطقة ب حتى يُسمح بإضافة شحنات جديدة أثناء الرحلة.',
    category: 'in_transit',
  },
  {
    key: 'MAX_IN_TRANSIT_ADDITIONS',
    label: 'أقصى عدد الإضافات أثناء الرحلة',
    unit: 'شحنة',
    type: 'count',
    defaultValue: 10,
    min: 1,
    max: 100,
    step: 1,
    explanation: 'الحد الأقصى للشحنات التي يمكن إضافتها للدفعة أثناء سير السائق.',
    category: 'in_transit',
  },
  {
    key: 'REQUIRE_COURIER_CONFIRMATION_FOR_ADDITION',
    label: 'طلب تأكيد السائق للإضافة',
    unit: 'نعم/لا',
    type: 'boolean',
    defaultValue: false,
    explanation: 'يستلزم موافقة السائق الصريحة قبل تعيين الشحنات الجديدة له أثناء الرحلة.',
    category: 'in_transit',
  },

  // ── 11. ترتيب المحطات الداخلية ──────────────────────────────────────────────
  {
    key: 'WEIGHT_STOP_DISTANCE',
    label: 'وزن المسافة بين المحطات (W_dist)',
    unit: 'نسبة',
    type: 'ratio',
    defaultValue: 0.6,
    min: 0,
    max: 1,
    step: 0.01,
    explanation: 'أثر المسافة الفعلية في تحديد ترتيب المحطات داخل المدينة. قيمة أعلى = تفضيل المحطات القريبة.',
    category: 'intra_city',
    weightGroup: 'intra_city_weights',
  },
  {
    key: 'WEIGHT_STOP_URGENCY',
    label: 'وزن أولوية المحطة (W_urg)',
    unit: 'نسبة',
    type: 'ratio',
    defaultValue: 0.4,
    min: 0,
    max: 1,
    step: 0.01,
    explanation: 'أثر درجة الأولوية في تحديد ترتيب المحطات داخل المدينة. قيمة أعلى = تفضيل المحطات الأكثر إلحاحاً.',
    category: 'intra_city',
    weightGroup: 'intra_city_weights',
  },
  {
    key: 'ENABLE_2_OPT_OPTIMIZATION',
    label: 'تفعيل تحسين المسار ثنائي الاتجاه (2-opt)',
    unit: 'نعم/لا',
    type: 'boolean',
    defaultValue: true,
    explanation: 'يُحسّن المسار بعد الترتيب الجشعي للمحطات باستخدام مبادلات ثنائية، يُقلل إجمالي المسافة داخل المدينة.',
    category: 'intra_city',
  },
  {
    key: 'MAX_2_OPT_ITERATIONS',
    label: 'أقصى تكرارات التحسين (2-opt)',
    unit: 'تكرار',
    type: 'count',
    defaultValue: 100,
    min: 10,
    max: 1000,
    step: 10,
    explanation: 'أقصى عدد محاولات المبادلة لكل مسار. كلما زاد العدد تحسّن المسار لكن استغرق وقتاً أطول في الحساب.',
    category: 'intra_city',
  },
  {
    key: 'MERCHANT_READY_TIME_REQUIRED',
    label: 'اشتراط وقت جاهزية التاجر',
    unit: 'نعم/لا',
    type: 'boolean',
    defaultValue: true,
    explanation: 'لن يزور السائق محطة الاستلام قبل إبلاغ التاجر بجاهزية طلبه للاستلام.',
    category: 'intra_city',
  },

  // ── 12. تعيين السائق ────────────────────────────────────────────────────────
  {
    key: 'WEIGHT_DRIVER_PROXIMITY',
    label: 'وزن قرب السائق (W_prox)',
    unit: 'نسبة',
    type: 'ratio',
    defaultValue: 0.5,
    min: 0,
    max: 1,
    step: 0.01,
    explanation: 'تأثير قرب السائق من منطقة الانطلاق على تقييمه. قيمة أعلى = تفضيل السائقين الأقرب.',
    category: 'driver',
    weightGroup: 'driver_weights',
  },
  {
    key: 'WEIGHT_DRIVER_CAPACITY',
    label: 'وزن ملاءمة السعة (W_cap)',
    unit: 'نسبة',
    type: 'ratio',
    defaultValue: 0.3,
    min: 0,
    max: 1,
    step: 0.01,
    explanation: 'تأثير مدى تطابق سعة مركبة السائق مع حجم الدفعة على تقييمه.',
    category: 'driver',
    weightGroup: 'driver_weights',
  },
  {
    key: 'WEIGHT_DRIVER_LOAD',
    label: 'وزن إرهاق السائق (W_load)',
    unit: 'نسبة',
    type: 'ratio',
    defaultValue: 0.2,
    min: 0,
    max: 1,
    step: 0.01,
    explanation: 'عقوبة التعب بناءً على ساعات القيادة اليوم. قيمة أعلى = عقوبة أشد للسائقين المتعبين.',
    category: 'driver',
    weightGroup: 'driver_weights',
  },
  {
    key: 'PROXIMITY_DECAY_LAMBDA',
    label: 'معامل تناقص القرب (λ)',
    unit: 'معامل',
    type: 'coefficient',
    defaultValue: 0.1,
    min: 0.01,
    max: 2,
    step: 0.01,
    explanation: 'يتحكم في سرعة انخفاض نقاط القرب مع زيادة المسافة. المعادلة: P = e^(−λ × المسافة). كلما زاد λ كلما كان الانخفاض أسرع.',
    category: 'driver',
  },
  {
    key: 'MAX_SHIFT_HOURS',
    label: 'أقصى ساعات الوردية',
    unit: 'ساعة',
    type: 'hours',
    defaultValue: 10,
    min: 4,
    max: 16,
    step: 0.5,
    explanation: 'أقصى ساعات عمل مسموح بها في الوردية الواحدة. تُستخدم لحساب معامل الإرهاق.',
    category: 'driver',
  },
  {
    key: 'TOP_DRIVERS_TO_NOTIFY',
    label: 'عدد السائقين في كل جولة',
    unit: 'سائق',
    type: 'count',
    defaultValue: 3,
    min: 1,
    max: 10,
    step: 1,
    explanation: 'عدد السائقين المتاحين الأعلى تقييماً الذين يُرسَل إليهم الإشعار في كل جولة تعيين.',
    category: 'driver',
  },
  {
    key: 'DRIVER_RESPONSE_TIMEOUT_SECONDS',
    label: 'مهلة استجابة السائق',
    unit: 'ثانية',
    type: 'seconds',
    defaultValue: 90,
    min: 30,
    max: 600,
    step: 10,
    explanation: 'الوقت الممنوح لمجموعة السائقين لقبول الدفعة قبل الانتقال للجولة التالية.',
    category: 'driver',
  },
  {
    key: 'MAX_DRIVER_ASSIGNMENT_ROUNDS',
    label: 'أقصى جولات التعيين',
    unit: 'جولة',
    type: 'count',
    defaultValue: 3,
    min: 1,
    max: 10,
    step: 1,
    explanation: 'أقصى جولات إشعار السائقين قبل تصعيد الدفعة للمشرف يدوياً.',
    category: 'driver',
  },

  // ── 13. إعدادات الأعطال ─────────────────────────────────────────────────────
  {
    key: 'ENABLE_BREAKDOWN_REPOOL',
    label: 'إعادة تجميع الشحنات عند العطل',
    unit: 'نعم/لا',
    type: 'boolean',
    defaultValue: true,
    explanation: 'يُعيد الشحنات غير المستلمة فعلياً إلى المتاحة تلقائياً عند إبلاغ السائق عن عطل.',
    category: 'breakdown',
  },
  {
    key: 'ALERT_DISPATCHER_ON_BREAKDOWN',
    label: 'تنبيه المشرف عند العطل',
    unit: 'نعم/لا',
    type: 'boolean',
    defaultValue: true,
    explanation: 'يُرسل تنبيهاً فورياً للمشرف عند إبلاغ السائق عن عطل، خاصةً للشحنات العالقة التي تحتاج تدخلاً يدوياً.',
    category: 'breakdown',
  },
];

export type SettingsValues = Record<string, number | boolean | string>;

export function getDefaultValues(): SettingsValues {
  return Object.fromEntries(
    SETTINGS_DEFINITIONS.map(s => [s.key, s.defaultValue])
  );
}

export function getWeightGroupSum(
  group: string,
  values: SettingsValues
): number {
  const keys = WEIGHT_GROUPS[group]?.keys ?? [];
  return keys.reduce((sum, k) => sum + (Number(values[k]) || 0), 0);
}

export function isWeightGroupValid(group: string, values: SettingsValues): boolean {
  const sum = getWeightGroupSum(group, values);
  return Math.abs(sum - 1) < 0.001;
}
